"""empty message

Revision ID: fe7494ff68ff
Revises: 6738ae174185
Create Date: 2021-05-16 22:18:54.762454

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe7494ff68ff'
down_revision = '6738ae174185'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('meetings', 'accepted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('meetings', 'accepted',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###
