"""empty message

Revision ID: 0862399722cd
Revises: 47e9204c7378
Create Date: 2021-05-06 12:56:27.278981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0862399722cd'
down_revision = '47e9204c7378'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('emailAddress', sa.String(length=255), nullable=False))
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.create_unique_constraint(None, 'users', ['emailAddress'])
    op.drop_column('users', 'email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'users', type_='unique')
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.drop_column('users', 'emailAddress')
    # ### end Alembic commands ###
