"""empty message

Revision ID: 47e9204c7378
Revises: ffdc0a98111c
Create Date: 2021-05-06 12:54:21.437993

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47e9204c7378'
down_revision = 'ffdc0a98111c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('companyName', sa.String(length=60), nullable=False))
    op.add_column('users', sa.Column('isVendor', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('name', sa.String(length=60), nullable=False))
    op.add_column('users', sa.Column('summary', sa.String(length=500), nullable=False))
    op.drop_constraint('users_username_key', 'users', type_='unique')
    op.create_unique_constraint(None, 'users', ['name'])
    op.create_unique_constraint(None, 'users', ['companyName'])
    op.drop_column('users', 'username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.VARCHAR(length=40), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.create_unique_constraint('users_username_key', 'users', ['username'])
    op.drop_column('users', 'summary')
    op.drop_column('users', 'name')
    op.drop_column('users', 'isVendor')
    op.drop_column('users', 'companyName')
    # ### end Alembic commands ###
